// AUTO-GENERATED by scripts/generate-materials-manifest.mjs — do not edit manually.

export interface MaterialItem {
  filename: string;
  href: string;
  title: string;
  category: string;
}

export interface MaterialCategoryLabels {
  ru: string;
  en: string;
}

/** category id → localized labels (from _taxonomy.json) */
export const MATERIAL_CATEGORY_LABELS: Record<string, MaterialCategoryLabels> = {
  "general": {
    "ru": "Прочие материалы",
    "en": "Other materials"
  },
  "analysis": {
    "ru": "Математический анализ",
    "en": "Mathematical analysis"
  },
  "algebra": {
    "ru": "Алгебра и структуры",
    "en": "Algebra and structures"
  },
  "sets": {
    "ru": "Теория множеств",
    "en": "Set theory"
  },
  "foundations": {
    "ru": "Основания, логика, вычислимость",
    "en": "Foundations, logic, computability"
  }
};

/** Preferred ordering of category ids for menus and sections */
export const MATERIAL_CATEGORY_ORDER: readonly string[] = ["analysis","algebra","sets","foundations","general"];

export const MATERIALS_ITEMS: MaterialItem[] = [
  {
    "filename": "algebra_structures_3_3_fixed.html",
    "href": "/Materials/algebra_structures_3_3_fixed.html",
    "title": "Алгебраические структуры · Теория решёток",
    "category": "algebra"
  },
  {
    "filename": "diagonal.html",
    "href": "/Materials/diagonal.html",
    "title": "Вычисление неподвижной точки арифметической формулы",
    "category": "foundations"
  },
  {
    "filename": "math_analysis_levels.html",
    "href": "/Materials/math_analysis_levels.html",
    "title": "Уровни формализации математического анализа",
    "category": "analysis"
  },
  {
    "filename": "test1.html",
    "href": "/Materials/test1.html",
    "title": "Теория множеств: Тест",
    "category": "sets"
  }
];
