// AUTO-GENERATED by scripts/generate-materials-manifest.mjs — do not edit manually.

export interface MaterialItem {
  filename: string;
  href: string;
  title: string;
  category: string;
  lang: 'ru' | 'en';
}

export interface MaterialCategoryLabels {
  ru: string;
  en: string;
}

/** category id → localized labels (from _taxonomy.json) */
export const MATERIAL_CATEGORY_LABELS: Record<string, MaterialCategoryLabels> = {
  "general": {
    "ru": "Прочие материалы",
    "en": "Other materials"
  },
  "maglish": {
    "ru": "Математика как иностранный",
    "en": "Mathematics as a Foreign Language"
  },
  "analysis": {
    "ru": "Математический анализ",
    "en": "Mathematical analysis"
  },
  "algebra": {
    "ru": "Алгебра и структуры",
    "en": "Algebra and structures"
  },
  "geometry": {
    "ru": "Геометрия и топология",
    "en": "Geometry and topology"
  },
  "sets": {
    "ru": "Теория множеств",
    "en": "Set theory"
  },
  "foundations": {
    "ru": "Основания, логика, вычислимость",
    "en": "Foundations, logic, computability"
  },
  "probability": {
    "ru": "Теория вероятностей и статистика",
    "en": "Probability theory and statistics"
  }
};

/** Preferred ordering of category ids for menus and sections */
export const MATERIAL_CATEGORY_ORDER: readonly string[] = ["maglish","analysis","algebra","geometry","sets","foundations","probability","general"];

export const MATERIALS_ITEMS: MaterialItem[] = [
  {
    "filename": "algebra_structures_3_3_fixed_en.html",
    "href": "/Materials/algebra_structures_3_3_fixed_en.html",
    "title": "Algebraic Structures · Lattice Theory",
    "category": "algebra",
    "lang": "en"
  },
  {
    "filename": "algebra_structures_3_3_fixed.html",
    "href": "/Materials/algebra_structures_3_3_fixed.html",
    "title": "Алгебраические структуры · Теория решёток",
    "category": "algebra",
    "lang": "ru"
  },
  {
    "filename": "chasles_en.html",
    "href": "/Materials/chasles_en.html",
    "title": "Motions of the Plane: Chasles' Theorem",
    "category": "geometry",
    "lang": "en"
  },
  {
    "filename": "chasles.html",
    "href": "/Materials/chasles.html",
    "title": "Движения плоскости: теорема Шаля",
    "category": "geometry",
    "lang": "ru"
  },
  {
    "filename": "complex_numbers.html",
    "href": "/Materials/complex_numbers.html",
    "title": "Комплексные числа: три конструкции одного поля",
    "category": "analysis",
    "lang": "ru"
  },
  {
    "filename": "complex_regularity.html",
    "href": "/Materials/complex_regularity.html",
    "title": "Регулярные функции: ряд Тейлора, интеграл Коши, формула Эйлера",
    "category": "analysis",
    "lang": "ru"
  },
  {
    "filename": "diagonal.html",
    "href": "/Materials/diagonal.html",
    "title": "Вычисление неподвижной точки арифметической формулы",
    "category": "foundations",
    "lang": "ru"
  },
  {
    "filename": "diophant_28_37.html",
    "href": "/Materials/diophant_28_37.html",
    "title": "28x + 37y = N — задача о новогодних подарках",
    "category": "general",
    "lang": "ru"
  },
  {
    "filename": "duality_en.html",
    "href": "/Materials/duality_en.html",
    "title": "One Object, Many Languages",
    "category": "algebra",
    "lang": "en"
  },
  {
    "filename": "duality.html",
    "href": "/Materials/duality.html",
    "title": "Один объект — разные языки",
    "category": "algebra",
    "lang": "ru"
  },
  {
    "filename": "galton_watson_process_en.html",
    "href": "/Materials/galton_watson_process_en.html",
    "title": "The Galton–Watson Process",
    "category": "probability",
    "lang": "en"
  },
  {
    "filename": "galton_watson_process.html",
    "href": "/Materials/galton_watson_process.html",
    "title": "Процесс Гальтона–Ватсона",
    "category": "probability",
    "lang": "ru"
  },
  {
    "filename": "henkin_construction_en.html",
    "href": "/Materials/henkin_construction_en.html",
    "title": "The Henkin Construction — An Interactive Demonstration",
    "category": "foundations",
    "lang": "en"
  },
  {
    "filename": "henkin_construction.html",
    "href": "/Materials/henkin_construction.html",
    "title": "Конструкция Хенкина — интерактивная демонстрация",
    "category": "foundations",
    "lang": "ru"
  },
  {
    "filename": "induction_en.html",
    "href": "/Materials/induction_en.html",
    "title": "On Mathematical Induction",
    "category": "foundations",
    "lang": "en"
  },
  {
    "filename": "induction.html",
    "href": "/Materials/induction.html",
    "title": "О математической индукции",
    "category": "foundations",
    "lang": "ru"
  },
  {
    "filename": "maglish_index_en.html",
    "href": "/Materials/maglish_index_en.html",
    "title": "Mathematics as a Foreign Language — Book Overview",
    "category": "maglish",
    "lang": "en"
  },
  {
    "filename": "maglish_index.html",
    "href": "/Materials/maglish_index.html",
    "title": "Математика как иностранный — краткое содержание книги",
    "category": "maglish",
    "lang": "ru"
  },
  {
    "filename": "math_analysis_levels_en.html",
    "href": "/Materials/math_analysis_levels_en.html",
    "title": "Levels of Formalization of Mathematical Analysis",
    "category": "analysis",
    "lang": "en"
  },
  {
    "filename": "math_analysis_levels.html",
    "href": "/Materials/math_analysis_levels.html",
    "title": "Уровни формализации математического анализа",
    "category": "analysis",
    "lang": "ru"
  },
  {
    "filename": "math_structures_en.html",
    "href": "/Materials/math_structures_en.html",
    "title": "How Mathematical Structures Are Constructed",
    "category": "algebra",
    "lang": "en"
  },
  {
    "filename": "math_structures.html",
    "href": "/Materials/math_structures.html",
    "title": "Как конструируются математические структуры",
    "category": "algebra",
    "lang": "ru"
  },
  {
    "filename": "second_order_arithmetic_en.html",
    "href": "/Materials/second_order_arithmetic_en.html",
    "title": "Hierarchy of Second-Order Arithmetic Theories",
    "category": "foundations",
    "lang": "en"
  },
  {
    "filename": "second_order_arithmetic.html",
    "href": "/Materials/second_order_arithmetic.html",
    "title": "Иерархия теорий арифметики второго порядка",
    "category": "foundations",
    "lang": "ru"
  },
  {
    "filename": "similarities_en.html",
    "href": "/Materials/similarities_en.html",
    "title": "Similarities of the Plane: Homothety and Rotational Homothety",
    "category": "geometry",
    "lang": "en"
  },
  {
    "filename": "similarities.html",
    "href": "/Materials/similarities.html",
    "title": "Подобия плоскости: гомотетия и поворотная гомотетия",
    "category": "geometry",
    "lang": "ru"
  },
  {
    "filename": "test1.html",
    "href": "/Materials/test1.html",
    "title": "Теория множеств: Тест",
    "category": "sets",
    "lang": "ru"
  }
];
